import type { FeedIntelligenceState } from './types';

export const feedIntelligenceState: FeedIntelligenceState = {
  generatedAt: '2026-05-12T22:00:00-04:00',
  sources: [
    {
      id: 'source-global-news',
      title: 'Global News Intake',
      url: 'https://socioprophet.news/feeds/global.xml',
      format: 'rss',
      scope: '/news/global',
      storagePolicy: 'localFirstSync',
      status: 'active',
      lastSeen: '2026-05-12T21:48:00-04:00',
    },
    {
      id: 'source-regulatory-watch',
      title: 'Regulatory Watch',
      url: 'https://socioprophet.news/feeds/law.xml',
      format: 'atom',
      scope: '/law/regulatory-watch',
      storagePolicy: 'hostedPrivate',
      status: 'watching',
      lastSeen: '2026-05-12T21:30:00-04:00',
    },
    {
      id: 'source-bearbrowser-capture',
      title: 'BearBrowser Captures',
      url: 'local://bearbrowser/feed-capture',
      format: 'htmlFallback',
      scope: '/capture/browser',
      storagePolicy: 'localOnly',
      status: 'review',
      lastSeen: '2026-05-12T21:12:00-04:00',
    },
  ],
  items: [
    {
      id: 'item-001',
      sourceId: 'source-global-news',
      title: 'Ticker proof-of-life event normalized into the reader stream',
      summary:
        'First slice confirms the 2020 sequence: ticker first, feed subscription second, federation later. RSS remains a derived view while the canonical event chain stays replayable.',
      canonicalUrl: 'https://socioprophet.news/items/ticker-proof-of-life',
      publishedAt: '2026-05-12T21:47:00-04:00',
      normalizedAt: '2026-05-12T21:48:13-04:00',
      topicScope: '/news/global',
      membraneDecision: 'admit',
      storagePolicy: 'localFirstSync',
      provenanceHash: 'spv0:2e9a7b1c88d4',
      eventRefs: ['FeedSubscribed', 'ItemFetched', 'ItemNormalized', 'ViewPublished'],
      entities: ['Socioprophet News', 'RSS', 'Kafka spine'],
      claims: ['ticker-gates-ingestion', 'rss-is-derived-view'],
    },
    {
      id: 'item-002',
      sourceId: 'source-regulatory-watch',
      title: 'Membrane hold applied to regulatory item pending provenance review',
      summary:
        'New Hope marks the item as hold because the source supplies incomplete timestamp and transform evidence. UI renders it without allowing publication or memory writeback.',
      canonicalUrl: 'https://socioprophet.news/items/regulatory-hold',
      publishedAt: '2026-05-12T21:24:00-04:00',
      normalizedAt: '2026-05-12T21:31:44-04:00',
      topicScope: '/law/regulatory-watch',
      membraneDecision: 'hold',
      storagePolicy: 'hostedPrivate',
      provenanceHash: 'spv0:7ac4b8d93210',
      eventRefs: ['ItemFetched', 'ItemNormalized', 'MembraneEvaluated'],
      entities: ['New Hope', 'PolicyFabric', 'Regulatory Watch'],
      claims: ['publication-requires-provenance', 'hold-prevents-writeback'],
    },
    {
      id: 'item-003',
      sourceId: 'source-bearbrowser-capture',
      title: 'BearBrowser capture queued as local-only evidence',
      summary:
        'Browser capture enters the reader as a reviewable local object. The system can scope it, annotate it, and request graph traversal without exposing private storage identity.',
      canonicalUrl: 'local://bearbrowser/captures/2026-05-12-001',
      publishedAt: '2026-05-12T21:11:00-04:00',
      normalizedAt: '2026-05-12T21:12:25-04:00',
      topicScope: '/capture/browser',
      membraneDecision: 'quarantine',
      storagePolicy: 'localOnly',
      provenanceHash: 'spv0:ca8014f70bbb',
      eventRefs: ['FeedDiscovered', 'ItemFetched', 'MembraneEvaluated'],
      entities: ['BearBrowser', 'SourceOS', 'MemoryMesh'],
      claims: ['capture-is-not-publication', 'local-only-by-default'],
    },
  ],
  events: [
    {
      id: 'event-001',
      type: 'FeedDiscovered',
      label: 'Feed discovered from source link or browser capture',
      status: 'complete',
      evidenceRef: 'eventlog://feed.discovered/001',
    },
    {
      id: 'event-002',
      type: 'FeedSubscribed',
      label: 'Subscription creates a slash-topic-scoped intake lane',
      status: 'complete',
      evidenceRef: 'eventlog://feed.subscribed/001',
    },
    {
      id: 'event-003',
      type: 'ItemFetched',
      label: 'Fetch preserves source URL, timestamp, and content hash',
      status: 'complete',
      evidenceRef: 'eventlog://item.fetched/001',
    },
    {
      id: 'event-004',
      type: 'ItemNormalized',
      label: 'RSS, Atom, JSON Feed, and HTML fallback normalize into one item contract',
      status: 'active',
      evidenceRef: 'eventlog://item.normalized/001',
    },
    {
      id: 'event-005',
      type: 'MembraneEvaluated',
      label: 'New Hope maps policy outcome to admit, hold, quarantine, or reject',
      status: 'active',
      evidenceRef: 'eventlog://newhope.membrane/001',
    },
    {
      id: 'event-006',
      type: 'MemoryProfileResolved',
      label: 'MemoryMesh attaches only after slash-topic scope and membrane admission',
      status: 'active',
      evidenceRef: 'eventlog://memory.profile/001',
    },
    {
      id: 'event-007',
      type: 'GraphViewPrepared',
      label: 'MeshRush prepares related claim, entity, source, and topic graph views',
      status: 'blocked',
      evidenceRef: 'eventlog://meshrush.graph/001',
    },
    {
      id: 'event-008',
      type: 'ViewPublished',
      label: 'RSS, Atom, JSON Feed, and ActivityPub remain derived views',
      status: 'blocked',
      evidenceRef: 'eventlog://view.published/001',
    },
  ],
  integrations: [
    {
      name: 'BearBrowser',
      role: 'Capture and provenance surface for pages, feeds, and browser evidence.',
      status: 'specified',
      contract: 'browser.feed.discovered, browser.page.captured, browser.item.extracted',
    },
    {
      name: 'SlashTopics',
      role: 'Public query and governance scope for each feed lane and saved search.',
      status: 'specified',
      contract: 'slash-topic scope, signed topic pack, deterministic receipt',
    },
    {
      name: 'New Hope',
      role: 'Internal membrane runtime for admission, hold, quarantine, and rejection.',
      status: 'specified',
      contract: 'NewHopeMembraneEvent mapped to admit, hold, quarantine, reject',
    },
    {
      name: 'MemoryMesh',
      role: 'Scoped recall and review-only writeback proposals after membrane admission.',
      status: 'specified',
      contract: 'SlashTopicMemoryProfile with no raw sensitive payload storage by default',
    },
    {
      name: 'MeshRush',
      role: 'Graph traversal, diffusion, crystallization, and reusable evidence structure.',
      status: 'pending',
      contract: 'Feed item graph view adapter for source, claim, entity, and topic nodes',
    },
  ],
};
