<template>
  <section class="nlb-page" aria-labelledby="nlb-title">
    <header class="nlb-hero">
      <div>
        <p class="nlb-kicker">NLBoot · Evidence Dashboard</p>
        <h1 id="nlb-title">Boot evidence artifacts</h1>
        <p class="nlb-lede">
          Read-only evidence records produced by an NLBoot run: plan, artifact cache, pre-exec
          proof, exec proof, Apple Silicon adapter, and boot-entry. All data is mock-fixture only —
          no host authority or real device actions.
        </p>
      </div>
      <div class="nlb-badge" aria-label="Evidence record count">
        <span class="nlb-badge-count">6</span>
        <span class="nlb-badge-label">record types</span>
      </div>
    </header>

    <!-- Plan record -->
    <article class="nlb-card" aria-labelledby="nlb-plan-title">
      <h2 id="nlb-plan-title">Plan record</h2>
      <p class="nlb-desc">Declarative boot plan generated by NLBoot before execution begins.</p>
      <div class="nlb-table-wrap">
        <table class="nlb-table">
          <thead>
            <tr>
              <th>Field</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in planRecord" :key="row.field">
              <td class="nlb-field">{{ row.field }}</td>
              <td>{{ row.value }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </article>

    <!-- Artifact cache record -->
    <article class="nlb-card" aria-labelledby="nlb-cache-title">
      <h2 id="nlb-cache-title">Artifact cache record</h2>
      <p class="nlb-desc">Content-addressed cache entries resolved during the plan phase.</p>
      <div class="nlb-table-wrap">
        <table class="nlb-table">
          <thead>
            <tr>
              <th>Artifact</th>
              <th>Digest</th>
              <th>Source</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="artifact in artifactCache" :key="artifact.name">
              <td class="nlb-field">{{ artifact.name }}</td>
              <td class="nlb-mono">{{ artifact.digest }}</td>
              <td>{{ artifact.source }}</td>
              <td>
                <span :class="`nlb-pill nlb-pill--${artifact.status}`">{{ artifact.status }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </article>

    <!-- Pre-exec proof -->
    <article class="nlb-card" aria-labelledby="nlb-preexec-title">
      <h2 id="nlb-preexec-title">Pre-exec proof</h2>
      <p class="nlb-desc">
        Attestation that pre-conditions were satisfied before execution was authorised.
      </p>
      <div class="nlb-grid nlb-grid--two">
        <div v-for="item in preExecProof" :key="item.check" class="nlb-check">
          <span :class="`nlb-dot nlb-dot--${item.result}`" aria-hidden="true" />
          <div>
            <strong>{{ item.check }}</strong>
            <p>{{ item.detail }}</p>
          </div>
        </div>
      </div>
    </article>

    <!-- Exec proof -->
    <article class="nlb-card" aria-labelledby="nlb-exec-title">
      <h2 id="nlb-exec-title">Exec proof</h2>
      <p class="nlb-desc">
        Post-execution attestation capturing exit status, timing, and output digest.
      </p>
      <div class="nlb-table-wrap">
        <table class="nlb-table">
          <thead>
            <tr>
              <th>Field</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in execProof" :key="row.field">
              <td class="nlb-field">{{ row.field }}</td>
              <td>{{ row.value }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </article>

    <!-- Apple Silicon adapter record -->
    <article class="nlb-card" aria-labelledby="nlb-adapter-title">
      <h2 id="nlb-adapter-title">Apple Silicon adapter record</h2>
      <p class="nlb-desc">
        Hardware capability report from the Apple Silicon boot adapter (mock fixture).
      </p>
      <div class="nlb-table-wrap">
        <table class="nlb-table">
          <thead>
            <tr>
              <th>Capability</th>
              <th>Detected</th>
              <th>Note</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="cap in appleAdapter" :key="cap.capability">
              <td class="nlb-field">{{ cap.capability }}</td>
              <td>
                <span :class="`nlb-pill nlb-pill--${cap.detected ? 'hit' : 'miss'}`">
                  {{ cap.detected ? 'yes' : 'no' }}
                </span>
              </td>
              <td>{{ cap.note }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </article>

    <!-- Boot-entry record -->
    <article class="nlb-card" aria-labelledby="nlb-entry-title">
      <h2 id="nlb-entry-title">Boot-entry record</h2>
      <p class="nlb-desc">
        EFI / boot-loader entry written (or verified) by this NLBoot run.
      </p>
      <div class="nlb-table-wrap">
        <table class="nlb-table">
          <thead>
            <tr>
              <th>Field</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in bootEntry" :key="row.field">
              <td class="nlb-field">{{ row.field }}</td>
              <td>{{ row.value }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </article>

    <footer class="nlb-card nlb-callout">
      <p>
        <strong>Non-goal:</strong> This dashboard displays evidence records only. It does not issue
        boot commands, modify EFI state, or interact with any host hardware.
      </p>
    </footer>
  </section>
</template>

<script setup lang="ts">
type KV = { field: string; value: string };
type ArtifactEntry = { name: string; digest: string; source: string; status: 'hit' | 'miss' | 'pending' };
type CheckEntry = { check: string; detail: string; result: 'pass' | 'fail' | 'warn' };
type CapabilityEntry = { capability: string; detected: boolean; note: string };

const planRecord: KV[] = [
  { field: 'plan_id', value: 'nlboot-plan-20260430-001' },
  { field: 'schema_version', value: '0.4.0' },
  { field: 'target_platform', value: 'apple-silicon-m3' },
  { field: 'os_image', value: 'sociosd-asahi-0.4.0-arm64.img' },
  { field: 'kernel_cmdline', value: 'quiet loglevel=3 sociosd.boot=nlboot' },
  { field: 'created_at', value: '2026-04-30T08:00:00Z' },
  { field: 'author', value: 'nlboot-agent@socioprophet' },
  { field: 'status', value: 'approved' },
];

const artifactCache: ArtifactEntry[] = [
  {
    name: 'sociosd-asahi-0.4.0-arm64.img',
    digest: 'sha256:4a3b2c1d…e9f8a7b6',
    source: 'oci://registry.socioprophet.io/nlboot/sociosd-asahi',
    status: 'hit',
  },
  {
    name: 'asahi-kernel-6.9.0-arm64.efi',
    digest: 'sha256:1f2e3d4c…b5a69870',
    source: 'oci://registry.socioprophet.io/nlboot/asahi-kernel',
    status: 'hit',
  },
  {
    name: 'nlboot-stub-0.4.0.efi',
    digest: 'sha256:dead0000…beef1234',
    source: 'oci://registry.socioprophet.io/nlboot/stub',
    status: 'hit',
  },
  {
    name: 'firmware-patch-rev12.bin',
    digest: 'sha256:00000000…00000000',
    source: 'oci://registry.socioprophet.io/nlboot/firmware-patches',
    status: 'miss',
  },
];

const preExecProof: CheckEntry[] = [
  { check: 'Artifact digests verified', detail: 'All cached digests match policy allowlist.', result: 'pass' },
  { check: 'Plan schema validates', detail: 'nlboot-plan-schema v0.4.0 — no violations.', result: 'pass' },
  { check: 'Policy decision: allow', detail: 'policy-fabric decision ID pfd-20260430-009 returned allow.', result: 'pass' },
  { check: 'Disk space ≥ 8 GiB', detail: '42 GiB free on /dev/nvme0n1p3.', result: 'pass' },
  { check: 'Firmware patch available', detail: 'firmware-patch-rev12.bin cache miss — using rev11 fallback.', result: 'warn' },
  { check: 'Secure Boot state', detail: 'Secure Boot is disabled on this platform; acceptable for dev target.', result: 'warn' },
];

const execProof: KV[] = [
  { field: 'exec_id', value: 'nlboot-exec-20260430-001' },
  { field: 'started_at', value: '2026-04-30T08:04:11Z' },
  { field: 'finished_at', value: '2026-04-30T08:07:43Z' },
  { field: 'duration_s', value: '212' },
  { field: 'exit_code', value: '0' },
  { field: 'output_digest', value: 'sha256:cafebabe…12345678' },
  { field: 'agent', value: 'nlboot-agent@socioprophet' },
  { field: 'attested_by', value: 'socioprophet-evidence-svc v0.3.1' },
];

const appleAdapter: CapabilityEntry[] = [
  { capability: 'ANE (Apple Neural Engine)', detected: true, note: 'Reported by sysfs; driver loaded.' },
  { capability: 'Unified Memory Architecture', detected: true, note: '24 GiB shared pool detected.' },
  { capability: 'GPU Metal compute', detected: true, note: 'Metal 3 available via Asahi DRM driver.' },
  { capability: 'Thunderbolt 4', detected: true, note: '2× TB4 ports enumerated.' },
  { capability: 'TouchID sensor', detected: false, note: 'Not enumerated under this boot mode.' },
  { capability: 'T2-equivalent SEP', detected: true, note: 'Secure Enclave Processor accessible.' },
];

const bootEntry: KV[] = [
  { field: 'entry_id', value: 'Boot0003' },
  { field: 'label', value: 'SocioProphet NLBoot (Asahi)' },
  { field: 'loader_path', value: '\\EFI\\NLBOOT\\nlboot-stub-0.4.0.efi' },
  { field: 'partition_guid', value: '01234567-89ab-cdef-0123-456789abcdef' },
  { field: 'attributes', value: 'active, boot-next-once' },
  { field: 'written_at', value: '2026-04-30T08:07:41Z' },
  { field: 'verified', value: 'true' },
];
</script>

<style scoped>
.nlb-page {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  color: var(--text, #f4f4f4);
}

.nlb-hero,
.nlb-card {
  border: 1px solid rgba(255, 255, 255, 0.14);
  border-radius: 18px;
  background: rgba(20, 24, 31, 0.82);
  box-shadow: 0 18px 48px rgba(0, 0, 0, 0.22);
}

.nlb-hero {
  display: flex;
  justify-content: space-between;
  gap: 2rem;
  padding: 1.5rem;
}

.nlb-kicker {
  margin: 0 0 0.4rem;
  color: var(--accent, #78a9ff);
  font-size: 0.78rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

h1,
h2,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 0.7rem;
  font-size: clamp(1.8rem, 4vw, 3rem);
  line-height: 1;
}

h2 {
  margin-bottom: 0.5rem;
  font-size: 1.1rem;
}

.nlb-lede,
.nlb-desc {
  color: rgba(255, 255, 255, 0.72);
  line-height: 1.55;
}

.nlb-lede {
  max-width: 760px;
  margin-bottom: 0;
}

.nlb-desc {
  margin-bottom: 0.9rem;
  font-size: 0.9rem;
}

.nlb-badge {
  min-width: 140px;
  align-self: stretch;
  display: grid;
  place-content: center;
  border-radius: 16px;
  background: linear-gradient(145deg, rgba(120, 169, 255, 0.22), rgba(36, 161, 72, 0.18));
  text-align: center;
}

.nlb-badge-count {
  display: block;
  font-size: 2.8rem;
  font-weight: 800;
}

.nlb-badge-label {
  color: rgba(255, 255, 255, 0.72);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.nlb-card {
  padding: 1rem 1.2rem;
}

.nlb-table-wrap {
  overflow-x: auto;
}

.nlb-table {
  width: 100%;
  border-collapse: collapse;
}

.nlb-table th,
.nlb-table td {
  padding: 0.6rem 0.5rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  text-align: left;
  font-size: 0.88rem;
}

.nlb-table th {
  color: rgba(255, 255, 255, 0.6);
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.nlb-field {
  font-weight: 600;
  color: rgba(255, 255, 255, 0.88);
  white-space: nowrap;
}

.nlb-mono {
  font-family: ui-monospace, 'SFMono-Regular', Consolas, monospace;
  font-size: 0.8rem;
  color: rgba(255, 255, 255, 0.75);
}

.nlb-pill {
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  padding: 0.15rem 0.5rem;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
}

.nlb-pill--hit {
  background: rgba(36, 161, 72, 0.2);
  color: #42be65;
}

.nlb-pill--miss {
  background: rgba(255, 131, 0, 0.18);
  color: #ff8300;
}

.nlb-pill--pending {
  background: rgba(255, 255, 255, 0.12);
  color: rgba(255, 255, 255, 0.7);
}

.nlb-grid {
  display: grid;
  gap: 0.85rem;
}

.nlb-grid--two {
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
}

.nlb-check {
  display: flex;
  align-items: flex-start;
  gap: 0.75rem;
}

.nlb-dot {
  flex-shrink: 0;
  width: 0.75rem;
  height: 0.75rem;
  margin-top: 0.3rem;
  border-radius: 50%;
}

.nlb-dot--pass {
  background: #42be65;
}

.nlb-dot--warn {
  background: #f1c21b;
}

.nlb-dot--fail {
  background: #fa4d56;
}

.nlb-check strong {
  display: block;
  font-size: 0.9rem;
}

.nlb-check p {
  margin: 0.2rem 0 0;
  font-size: 0.82rem;
  color: rgba(255, 255, 255, 0.65);
}

.nlb-callout p {
  margin: 0;
  color: rgba(255, 255, 255, 0.72);
  font-size: 0.88rem;
}

@media (max-width: 760px) {
  .nlb-hero {
    flex-direction: column;
  }

  .nlb-badge {
    min-height: 120px;
  }
}
</style>
